## 0.jupyter notebook 的快捷键
> - enter 编辑<br>
> - esc 退出编辑<br>
> - m markdown模式<br>
> - y code模式<br>
> - dd 删除选中的单元<br>
> - shift+enter 运行此单元，新建下个单元<br>
> - ctrl+enter 运行此单元<br>
> - a 在上方插入新单元<br>
> - b 在下方插入新单元

# 一、ndarray

## 1.numpy的特性

### 多维性

In [1]:
import numpy as np

In [10]:
arr1 = np.array(5)
print(arr1)
print('arr1的维度:',arr1.ndim)

5
arr1的维度: 0


In [11]:
arr2 = np.array([1,2,3,4])
print(arr2)
print('arr2的维度：',arr2.ndim)

[1 2 3 4]
arr2的维度： 1


In [12]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])  #注意二维的得搞两层列表
print(arr3)
print('arr3的维度:',arr3.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr3的维度: 2


In [13]:
arr4 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])  #注意三维的得搞三层列表
print(arr4)
print('arr4的维度:',arr4.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
arr4的维度: 3


### 同质性

In [14]:
arr5 = np.array([1,'hello'])  #不同的数据类型会被强制转换成相同的数据类型
arr6 = np.array([1,1.5])
print(arr5)
print(arr6)

['1' 'hello']
[1.  1.5]


## 2.numpy的属性

In [40]:
arr = np.array([[1,2,3],[4,5,6]])
print('arr的数组的形状:',arr.shape)
print('arr的维度数量:',arr.ndim)
print('arr的元素个数:',arr.size)
print('arr的元素类型:',arr.dtype)
print('arr的转置:\n',arr.T)
print('arr的单个元素占用的内存字节数:',arr.itemsize)
print('arr的数组总内存占用量:',arr.nbytes)
print('arr的内存存储方式（是否连续存储）（高级优化）:\n',arr.flags)

arr的数组的形状: (2, 3)
arr的维度数量: 2
arr的元素个数: 6
arr的元素类型: int64
arr的转置:
 [[1 4]
 [2 5]
 [3 6]]
arr的单个元素占用的内存字节数: 8
arr的数组总内存占用量: 48
arr的内存存储方式（是否连续存储）（高级优化）:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## 3.ndarray的创建

- **基础构造**：<br>*适用于手动构建小规模数组或复制已有数据。*<br>`np.array()` `np.copy()`
- **预定义形状填充**：<br>*用于快速初始化固定形状的数组（如全0占位、全1初始化）*<br>`np.zeros()` `np.ones()` `np.empty()` `np.full()`
- **基于数值范围生成**：<br>*生成数值序列，常用于模拟时间序列、坐标网格等。*<br>`np.arange()` `np.linspace` `np.logspace()`
- **特殊矩阵生成**：<br>*数学运算专用（如线性代数中的单位矩阵）。*<br>`np.eye()` `np.diag()`
- **随机数组生成**：<br>*模拟实验数据、初始化神经网络权重等场景。*<br>`np.random.rand()` `np.random.randn()` `np.random.randint()`
- **高级构造方法**：<br>*处理非结构化数据（文件、字符串）或通过函数生成复杂数组。*<br>`np.array()` `np.loadtxt()` `np.fromfunction()`

### 预定义形状填充

In [51]:
arr = np.zeros(shape=(2,3),dtype=int)
print('arr:\n',arr)
print('arr type:',arr.dtype)

arr:
 [[0 0 0]
 [0 0 0]]
arr type: int64


In [52]:
arr = np.ones((3,2),int)
print('arr:\n',arr)
print('arr type:',arr.dtype)

arr:
 [[1 1]
 [1 1]
 [1 1]]
arr type: int64


In [53]:
arr = np.empty((2,3),int)  # 随机生成的
print('arr:\n',arr)
print('arr type:',arr.dtype)

arr:
 [[0 0 0]
 [0 0 0]]
arr type: int64


In [54]:
arr = np.full((2,3),2025,int)
print('arr:\n',arr)
print('arr type:',arr.dtype)

arr:
 [[2025 2025 2025]
 [2025 2025 2025]]
arr type: int64


In [55]:
arr = np.full_like(arr2,20,int)  # 形状（行数、列数）一样
print('arr:\n',arr)
print('arr type:',arr.dtype)

arr:
 [[20 20]
 [20 20]
 [20 20]]
arr type: int64


### 基于数值范围生成

In [48]:
# 等差数列
arr = np.arange(0,11,2)  # start,end(not included),step
print(arr)

[ 0  2  4  6  8 10]


In [49]:
# 等间隔数列
arr = np.linspace(1,15,5) # start,end(default include),number of pieces
print(arr)

[ 1.   4.5  8.  11.5 15. ]


In [50]:
# 对数间隔数列（等比数列）
arr = np.logspace(1,7,4,base=2) # 把从2^1到2^7分成4等份
print(arr)

[  2.   8.  32. 128.]


### 特殊矩阵的生成

In [46]:
# 单位矩阵: 主对角线上的数字为1，其它位置为0
arr1 = np.eye(3, dtype=int)
arr2 = np.eye(3, 2, dtype=float)
print('arr1:\n', arr1)
print('arr2:\n', arr2)

arr1:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
arr2:
 [[1. 0.]
 [0. 1.]
 [0. 0.]]


In [47]:
# 对角矩阵： 主对角线上为非零的数，其他的位置为0
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### 随机数组的生成

In [41]:
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2,3)  # 生成2行3列的0~1之间的随机数
print(arr)

[[0.03588959 0.69175758 0.37868094]
 [0.51851095 0.65795147 0.19385022]]


In [42]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3,6,(2,3))  # 生成2行3列的3~6之间的随机数
print(arr)

[[3.81694921 5.1558178  5.34901083]
 [5.55098292 5.32573468 3.10999292]]


In [43]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3, 30, (3,2))  # 生成3行2列的3~30之间的随机整数
print(arr)

[[ 9 29]
 [16 14]
 [29 28]]


In [44]:
# 生成随机数列（正态分布）
arr = np.random.randn(2,3) #生成均值为0，标准差为1的2行3列的正态分布随机数
print(arr)

[[ 0.6226121  -0.42687316  0.08443397]
 [ 0.61563566  0.53843148 -0.63997574]]


In [45]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(5,10,(2,3))
print(arr)

[[8 7 9]
 [7 6 9]]


## 4.ndarray的数据类型

- 布尔类型 bool
- 整数类型
    - 有符号：int8、int16、int32、int64
    - 无符号：uint8、uint16、uint32、uint64
- 浮点类型
    - float16、float32、float64、float128
- 复数类型
    - complex64、complex128、complex256

In [39]:
arr1 = np.array([0, 127, 255], dtype='uint8') # 无符号8bit整数 0~255
arr2 = np.array([0, -128, 127], dtype='int8') # 有符号8bit整数 -128~127
arr3 = np.array([0, 127, 255], dtype='bool') # 布尔类型 0为False，非0为True
print(arr1, arr1.itemsize, arr1.nbytes, arr1.dtype)
print(arr2, arr2.itemsize, arr2.nbytes, arr2.dtype)
print(arr3, arr3.itemsize, arr3.nbytes, arr3.dtype)

[  0 127 255] 1 3 uint8
[   0 -128  127] 1 3 int8
[False  True  True] 1 3 bool


# 二、numpy

## 1.numpy的索引与切片

- 索引/切片类型： 描述/用法
- 基本索引： 通过整数索引直接访问元素，索引从0开始
- 行/列切片： 使用冒号`:`切片语法选择行或列的子集
- 连续切片： 从起始索引到结束索引按步长切片
- 使用slice函数： 通过`slice(start, stop, step)`定义切片规则
- 布尔索引： 通过布尔条件筛选满足条件的元素，支持逻辑运算符`&` `|`

### 一维数组的索引与切片

In [60]:
arr = np.random.randint(1, 100, 15)
print(arr)

[30 46  7 64 79 25 19 94 34 79 43 95  4 19 71]


In [64]:
print(arr[10])
print(arr[:]) # 获取全部数据
print(arr[2:10]) # start:end+1 左包右不包
print(arr[slice(2,10,3)]) # start, end, step 左包右不包
print(arr[ (arr < 50) & (arr > 30) ]) # 布尔索引


43
[30 46  7 64 79 25 19 94 34 79 43 95  4 19 71]
[ 7 64 79 25 19 94 34 79]
[ 7 25 34]
[46 34 43]


### 二维数组的索引与切片

In [65]:
arr = np.random.randint(1, 100, (3,5))
print(arr)

[[53 23 15  5 28]
 [76  9  7 27 80]
 [83 79 11 34 86]]


In [72]:
print(arr[1, 2])
print(arr[ :, 3 ])
print(arr[2, 1:4])
print(arr[ arr < 50 ]) # 整个列表中小于50的数
print(arr[2][ arr[2] > 50]) # 第三行中大于50的数

7
[ 5 27 34]
[79 11 34]
[23 15  5 28  9  7 27 11 34]
[83 79 86]


## 2.ndarray的运算

- numpy一维数组算术运算（数组与数组）

In [78]:
# numpy一维数组算术运算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(f"a={a}\nb={b}\nnumpy一维数组算术运算：")
print('add:', a + b)
print('sub:', a - b)
print('mul:', a * b)
print('div:', a / b)
print('power:', a ** b)

a=[1 2 3]
b=[4 5 6]
numpy一维数组算术运算：
add: [5 7 9]
sub: [-3 -3 -3]
mul: [ 4 10 18]
div: [0.25 0.4  0.5 ]
power: [  1  32 729]


In [83]:
# 原生python计算
c = [1, 2, 3]
d = [4, 5, 6]
print('c:', c)
print('d:', d)
print('原生python计算：')
print('add:', c + d)
try:
    print('sub:', c - d)
except Exception as e:
    print("\033[31mError:\033[0m", e)

c: [1, 2, 3]
d: [4, 5, 6]
原生python计算：
add: [1, 2, 3, 4, 5, 6]
Error: unsupported operand type(s) for -: 'list' and 'list'


- numpy二维数组算术运算（数组与数组）

In [90]:
# numpy二维数组算术运算
a = np.random.randint(1,5,(2,3))
b = np.random.randint(1,5,(2,3))
print(f"a=\n{a}\nb=\n{b}\nnumpy二维数组算术运算：")
print('add:\n', a + b)
print('sub:\n', a - b)
print('mul:\n', a * b)
print('div:\n', a / b)
print('power:\n', a ** b)

a=
[[1 4 1]
 [3 3 4]]
b=
[[1 4 3]
 [4 3 4]]
numpy二维数组算术运算：
add:
 [[2 8 4]
 [7 6 8]]
sub:
 [[ 0  0 -2]
 [-1  0  0]]
mul:
 [[ 1 16  3]
 [12  9 16]]
div:
 [[1.         1.         0.33333333]
 [0.75       1.         1.        ]]
power:
 [[  1 256   1]
 [ 81  27 256]]


- numpy一维数组算术运算（数组与标量）

In [92]:
a = np.array([1, 2, 3])
n = 3
print(a)
print('numpy数组与标量的运算：')
print(a + n)
print(a - n)
print(a * n)
print(a / n)
print(a ** n)

[1 2 3]
numpy数组与标量的运算：
[4 5 6]
[-2 -1  0]
[3 6 9]
[0.33333333 0.66666667 1.        ]
[ 1  8 27]


- 广播机制（两数组形状不相同）

In [3]:
a = np.array([1, 2, 3]) # 1*3
b = np.array([[4], [5], [6]]) # 3*1
print(f"a=\n{a}\nb=\n{b}\na+b=")
print(a + b)

a=
[1 2 3]
b=
[[4]
 [5]
 [6]]
a+b=
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
"""
a:
1 2 3       1 2 3
       -->  1 2 3
            1 2 3

b:
4        4 4 4
5   -->  5 5 5
6        6 6 6

"""

- 矩阵乘法（用@符号）

In [2]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(f"a=\n{a}\nb=\n{b}\nnumpy矩阵乘法：")
print("a x b = \n", a @ b)

a=
[[1 2]
 [3 4]]
b=
[[5 6]
 [7 8]]
numpy矩阵乘法：
a x b = 
 [[19 22]
 [43 50]]


## 3.numpy常用函数

- 基本数学函数
    - `np.sqrt(x)` `np.exp(x)` `np.log(x)` `np.sin(x)` `np.abs(x)` `np.power(a, b)` `np.round(x, n)` `np.ceil(x)` `np.floor(x)` `np.isnan(x)`
- 统计函数
    - `np.sum(x)` `np.cumsum(x)` `np.cumprod(x)` `np.mean(x)` `np.median(x)` `np.std(x)` `np.var(x)` `np.min(x)` `np.max(x)` `np.argmin(x)` `np.argmax(x)` `np.percentile(x, q)`
- 比较函数
    - `np.greater(a, b)` `np.less(a, b)` `np.equal(a, b)` `np.not_equal(a, b)` `np.logical_and(a, b)` `np.logical_or(a, b)` `np.logical_not(x)` `np.any(x)` `np.all(x)` `np.where(condition, x, y)` `np.select(conditions, choices, default)`
- 排序函数
    - `np.sort(x)` `x.sort()` `np.argsort(x)` `np.lexsort(keys)` `np.searchsorted(x, v)` `np.partition(x, kth)` `np.argpartition(x, kth)`
- 去重函数
    - `np.unique(x)`
- 其他函数
    - `np.concatenate((a, b))` `np.split(x, indices_or_sections)` `np.reshape(x, newshape)` `np.copy(x)` `np.isnan(x)` `np.transpose(x)` `np.ravel(x)`
- 线性代数函数⭐
    - `np.dot(a, b)` `np.linalg.inv(A)` `np.linalg.eig(A)` `np.linalg.svd(A)`
- 傅里叶变换函数⭐
    - `np.fft.fft(x)` `np.fft.ifft(x)` `np.fft.fft2(x)` `np.fft.ifft2(x)`

### 3.1 基本数学函数

In [38]:
# 计算平方根 X^0.5
print(np.sqrt(4))
print(np.sqrt([1, 4, 9]))

# 计算指数 e^x
print(np.exp(1))
print(np.exp([1, 2, 3]))

# 计算自然对数 lnX
print(np.log(np.e))
print(np.log([1, np.e, np.e**2, np.e**3]))

2.0
[1. 2. 3.]
2.718281828459045
[ 2.71828183  7.3890561  20.08553692]
1.0
[0. 1. 2. 3.]


In [39]:
# 计算正弦值
print(np.sin([0, np.pi/2, np.pi, 3*np.pi/2]))
# 计算余弦值
print(np.cos([0, np.pi/2, np.pi, 3*np.pi/2]))
# 计算正切值
print(np.tan([0, np.pi/2, np.pi, 3*np.pi/2]))

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]
[ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16  5.44374645e+15]


In [41]:
# 计算绝对值
print(np.abs([1, -2, -5]))

# 计算a的b次幂 （a，b）
print(np.power(5, 2))

# 四舍六入五成双
print(np.round([1.5, 2.5, 3.5, 4.5]))
print(np.round([1.45, 2.45, 3.65, 4.65, 5.55, 6.55],1))


[1 2 5]
25
[2. 2. 4. 4.]
[1.4 2.4 3.6 4.6 5.6 6.6]


In [42]:
# 向上取整
print(np.ceil([1.2, 2.5, 3.7]))

# 向下取整
print(np.floor([1.2, 2.5, 3.7]))

# 检测缺失值NaN
print(np.isnan([1.2, 2.5, 3.7, np.nan]))

[2. 3. 4.]
[1. 2. 3.]
[False False False  True]


### 3.2 统计函数

In [ ]:
# variance 方差
# standard deviation 标准差

In [45]:
arr1 = np.random.randint(1, 20, 10)
arr2 = np.random.randint(1, 10, 5)
print(arr1)
print(arr2)

# 求和
print('sum:',np.sum(arr1))
# 累加
print('cumsum:',np.cumsum(arr1))
# 累乘
print('cumprod:',np.cumprod(arr2))

[ 1 12  5  6  3  1  3  5 16 18]
[7 7 1 8 8]
sum: 70
cumsum: [ 1 13 18 24 27 28 31 36 52 70]
cumprod: [   7   49   49  392 3136]


In [49]:
print('arr1:',arr1)
print('arr2:',arr2)

# 平均值
print('mean 1:',np.mean(arr1))
print('mean 2:',np.mean(arr2))

# 中位数
print('median 1:',np.median(arr1))
print('median 2:',np.median(arr2))

# 标准差
print('standard deviation 1:',np.std(arr1))
print('standard deviation 2:',np.std(arr2))

# 方差
print('variance 1:',np.var(arr1))
print('variance 2:',np.var(arr2))

# 最大值
print('max 1:', np.max(arr1), '\tindex max (argmax) 1:', np.argmax(arr1))

# 最小值
print('min 2:', np.min(arr2), '\tindex min (argmin) 2:', np.argmin(arr2))

# 分位数
print('pencentile 1:', np.percentile(arr1, 25))
print('pencentile 2:', np.percentile(arr2, 50))

arr1: [ 1 12  5  6  3  1  3  5 16 18]
arr2: [7 7 1 8 8]
mean 1: 7.0
mean 2: 6.2
median 1: 5.0
median 2: 7.0
standard deviation 1: 5.830951894845301
standard deviation 2: 2.6381811916545836
variance 1: 34.0
variance 2: 6.959999999999999
max 1: 18 	index max (argmax) 1: 9
min 2: 1 	index min (argmin) 2: 2
pencentile 1: 3.0
pencentile 2: 7.0


### 3.3 比较函数

In [62]:
# 比较大小

# 是否大于
print('1:', np.greater([3, 4, 5, 6], 4.5))
print('2:', np.greater([3, 5, 8], [3, 6, 7]))  # 对应位置比较，形状要保持一致
# 是否小于
print('3:', np.less([3, 4, 5, 6], 4.5))
# 是否等于
print('4:', np.equal([3, 4, 5, 6], 5))
print('5:', np.equal([3, 5, 7], [3, 6, 7]))
# 是否不等于
print('6:', np.not_equal([3, 4, 5, 6], 5))

1: [False False  True  True]
2: [False False  True]
3: [ True  True False False]
4: [False False  True False]
5: [ True False  True]
6: [ True  True False  True]


In [64]:
print(np.logical_and([1, 0], [1, 1]))  # 逻辑与
print(np.logical_or([1, 0], [0, 1]))  # 逻辑或
print(np.logical_not([1, 0]))  # 逻辑非

[ True False]
[ True  True]
[False  True]


In [67]:
# 检查元素是否至少有一个元素为True
print(np.any([0, 0, 1]))
# 检查元素是否全为True
print(np.all([1, 0, 1]))

True
False


In [76]:
# 自定义条件
# np.where(判断条件, 条件为真时执行, 条件为假时执行)
arr = np.random.randint(1, 15, 10)
print(arr)
print(np.where(arr > 7, 1, 0))
print(np.where(arr < 6, arr, 0))
print(np.where([True, False, True], [1, 2, 3], [4, 5, 6]))
print(np.where([[True, False], [True, True]], [[1, 2], [3, 4]], [[9, 8], [7, 6]]))

[ 6  6  7  2  6  6 14  7 13  1]
[0 0 0 0 0 0 1 0 1 0]
[0 0 0 2 0 0 0 0 0 1]
[1 5 3]
[[1 8]
 [3 4]]


In [83]:
# 嵌套条件判断
score = np.random.randint(1, 100, 20)
print(score)
print(np.where(score > 80, 'good',
               np.where(score > 60, 'medium', 'bad')))

[66 87 16 14 98 55 65 23 57 98 79 69 46 70 80 50 59 78 53 77]
['medium' 'good' 'bad' 'bad' 'good' 'bad' 'medium' 'bad' 'bad' 'good'
 'medium' 'medium' 'bad' 'medium' 'medium' 'bad' 'bad' 'medium' 'bad'
 'medium']


In [88]:
# np.select(条件, 返回的结果)
print(np.select([score > 80, (score>=60) & (score<=80), score < 60],
                ['good', 'medium', 'bad'],
                default='unknown'))

['medium' 'good' 'bad' 'bad' 'good' 'bad' 'medium' 'bad' 'bad' 'good'
 'medium' 'medium' 'bad' 'medium' 'medium' 'bad' 'bad' 'medium' 'bad'
 'medium']


### 3.4 排序函数

In [94]:
# 排序函数 sort()  np.sort()  np.argsort()
arr1 = np.random.randint(1, 100, 10)
arr2 = np.random.randint(1, 100, 10)
print('arr1:', arr1)
arr1.sort()  # python原生排序，会改变arr的值
print(arr1)
print('arr2:', arr2)
print(np.sort(arr2))  # numpy排序，不会改变arr2的值
print(np.argsort(arr2))  # numpy排序后的数对应的原数组的下标
print(arr2)

arr1: [76 69  7 69 48  4 77 53 79 16]
[ 4  7 16 48 53 69 69 76 77 79]
arr2: [21 59 24 80 14 86 49 50 70 42]
[14 21 24 42 49 50 59 70 80 86]
[4 0 2 9 6 7 1 8 3 5]
[21 59 24 80 14 86 49 50 70 42]


### 3.5 去重函数

In [130]:
# 去重函数
print(np.unique([0, 2 ,2, 3, 5, 6, 1, 3]))  # 去重并排序

[0 1 2 3 5 6]


### 3.6 其他函数

In [117]:
# 数组的拼接
print(arr1 + arr2)  # 各个位置分别相加
print(np.concatenate((arr1, arr2)))  # 将两个数组拼接在一起

[ 25  66  40 128  67 155 118 126 147 121]
[ 4  7 16 48 53 69 69 76 77 79 21 59 24 80 14 86 49 50 70 42]


In [118]:
# 数组的分割
print(arr1)
print(np.split(arr1, 5))  # 要能等分的份数
print(np.split(arr1, [3, 6, 8]))  # 手动输入分割的位置

[ 4  7 16 48 53 69 69 76 77 79]
[array([4, 7], dtype=int32), array([16, 48], dtype=int32), array([53, 69], dtype=int32), array([69, 76], dtype=int32), array([77, 79], dtype=int32)]
[array([ 4,  7, 16], dtype=int32), array([48, 53, 69], dtype=int32), array([69, 76], dtype=int32), array([77, 79], dtype=int32)]


In [129]:
x = np.random.randint(1, 10, (3, 4))
print('x:', x)

# 将数组展平, 不会改变原数组
print('np.ravel(x):\n', np.ravel(x))

# 数组的转置, 不会改变原数组
print('np.transpose(x):\n', np.transpose(x))

# 数组的形状改变, 不会改变原数组
print('np.reshape(x, (2,6)):\n', np.reshape(x, (2,6)))
print('x:', x)

x: [[7 1 7 4]
 [4 9 9 9]
 [3 4 3 1]]
np.ravel(x):
 [7 1 7 4 4 9 9 9 3 4 3 1]
np.transpose(x):
 [[7 4 3]
 [1 9 4]
 [7 9 3]
 [4 9 1]]
np.reshape(x, (2,6)):
 [[7 1 7 4 4 9]
 [9 9 3 4 3 1]]
x: [[7 1 7 4]
 [4 9 9 9]
 [3 4 3 1]]


## 4. 小练习

- 具体题目看老师PPT，这里仅做练手

In [140]:
"""
test 1: 温度数据分析
"""
temp = np.array([28, 30, 29, 31, 32, 30, 29])
print('温度：', temp)
print('平均气温：%.3f' % np.mean(temp))
print('最高气温:', np.max(temp))
print('最低气温:', np.min(temp))
# solution 1
print('气温超过30摄氏度的天数为：', len(temp[temp > 30])) # 布尔索引，temp必须是ndarray
# solution 2
print('气温超过30摄氏度的天数为：', np.sum(np.greater(temp, 30)))  # temp可以是ndarray，也可以是普通python列表
# solution 3
print('气温超过30摄氏度的天数为：', np.sum(np.where(temp > 30, 1, 0))) # temp必须是ndarray

温度： [28 30 29 31 32 30 29]
平均气温：29.857
最高气温: 32
最低气温: 28
气温超过30摄氏度的天数为： 2


In [144]:
"""
test 2: 学生成绩统计
"""
scores = np.array([85, 90, 78, 92, 88])
print('学生成绩：', scores)
print('平均分：', np.mean(scores))
print('中位数：', np.median(scores))
print('标准差：%.3f' % np.std(scores))
print('10分制：', scores / 10)

学生成绩： [85 90 78 92 88]
平均分： 86.6
中位数： 88.0
标准差：4.883
10分制： [8.5 9.  7.8 9.2 8.8]


In [148]:
"""
test 3: 矩阵运算
"""
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('A:\n', A)
print('B:\n', B)
print('A的转置（不影响原数组）：\n', A.T)
print('逐元素加法：\n', A + B)
print('逐元素乘法：\n', A * B)
print('矩阵乘法（点积）：\n', A @ B)
print('矩阵乘法（点积）：\n', np.dot(A, B))

A:
 [[1 2]
 [3 4]]
B:
 [[5 6]
 [7 8]]
A的转置（不影响原数组）：
 [[1 3]
 [2 4]]
逐元素加法：
 [[ 6  8]
 [10 12]]
逐元素乘法：
 [[ 5 12]
 [21 32]]
矩阵乘法（点积）：
 [[19 22]
 [43 50]]
矩阵乘法（点积）：
 [[19 22]
 [43 50]]


In [156]:
"""
test 4: 随机数据生成
"""
arr = np.random.randint(0, 10, (3, 4))
print('arr:\n', arr)
print('每列的最大值：\n', np.max(arr, axis = 0))
print('每行的最小值：\n', np.min(arr, axis = 1))

# solution 1 函数
print('将数组中的所有奇数替换为 -1：\n', np.where(arr % 2 == 1, -1, arr))

# solution 2 索引
arr[(arr % 2) == 1] = -1
print('将数组中的所有奇数替换为 -1：\n', arr)

arr:
 [[9 8 0 8]
 [5 9 0 9]
 [6 5 3 1]]
每列的最大值：
 [9 9 3 9]
每行的最小值：
 [0 0 1]
将数组中的所有奇数替换为 -1：
 [[-1  8  0  8]
 [-1 -1  0 -1]
 [ 6 -1 -1 -1]]
将数组中的所有奇数替换为 -1：
 [[-1  8  0  8]
 [-1 -1  0 -1]
 [ 6 -1 -1 -1]]


In [163]:
"""
test 5: 数组变形
"""
arr = np.arange(1, 13)
print('arr:\n', arr)
arr = np.reshape(arr, (3, 4))
print('将数组变形为 3x4 的二维数组：\n', arr)
print('每行的和：\n', np.sum(arr, axis = 1))  # axis = 1 表示 行
print('每列的平均值：\n', np.mean(arr, axis = 0))  # axis = 0 表示 列
print('展平成一维数组：\n', np.ravel(arr))

arr:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
将数组变形为 3x4 的二维数组：
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和：
 [10 26 42]
每列的平均值：
 [5. 6. 7. 8.]
展平成一维数组：
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [165]:
"""
test 6: 布尔索引
"""
arr = np.random.randint(0, 20, (5, 5))
print('arr:\n', arr)
print('找出数组中大于10的元素：\n', arr[arr > 10])
arr[arr > 10] = 0
print('将数组中大于 10 的元素替换为 0：\n', arr)

arr:
 [[11  0 11  8 10]
 [11  5 15  8  2]
 [19 19 14  3  3]
 [ 7  9  9  9  3]
 [14 18 12  3  9]]
找出数组中大于10的元素：
 [11 11 11 15 19 19 14 14 18 12]
将数组中大于 10 的元素替换为 0：
 [[ 0  0  0  8 10]
 [ 0  5  0  8  2]
 [ 0  0  0  3  3]
 [ 7  9  9  9  3]
 [ 0  0  0  3  9]]


In [169]:
"""
test 7: 统计函数应用
"""
total = np.array([120, 135, 110, 125, 130, 140])
print('total:\n', total)
print('销售额 总和：', np.sum(total))
print('销售额 均值：%.3f' % np.mean(total))
print('销售额 方差：%.3f' % np.var(total))
print('销售额最高的月份：', np.argmax(total) + 1 )  # 从0开始索引的，所以要加1
print('销售额最低的月份：', np.argmin(total) + 1 )  # 从0开始索引的，所以要加1

total:
 [120 135 110 125 130 140]
销售额 总和： 760
销售额 均值：126.667
销售额 方差：97.222
销售额最高的月份： 6
销售额最低的月份： 3


In [173]:
"""
test 8: 数组拼接
"""
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print('A:', A)
print('B:', B)
C = np.concatenate([A, B])
print('A和B水平拼接：', C)
print('A和B垂直拼接：\n', np.reshape(C, (2, 3)))

A: [1 2 3]
B: [4 5 6]
A和B水平拼接： [1 2 3 4 5 6]
A和B垂直拼接：
 [[1 2 3]
 [4 5 6]]


In [176]:
"""
test 9: 数组拼接
"""
arr = np.random.randint(1, 5, (2,3))
print('arr:\n', arr)
arr, counts = np.unique(arr, return_counts = True)
print('去重并排序：', arr)
print('次数:', counts)


arr:
 [[3 1 2]
 [2 1 4]]
去重并排序： [1 2 3 4]
次数: [2 2 1 1]


In [182]:
"""
test 10: 综合应用
"""
sell = np.array([20, 25, 22, 30, 28])
cost = np.array([15, 18, 16, 22, 20])
print('sell:', sell)
print('cost:', cost)
profit = sell - cost
print('利润：', profit)
print('利润的平均值：', np.mean(profit))
print('利润的标准差：%.3f' % np.std(profit))
print(f'利润最高的天数有 {len(profit[profit == np.max(profit)])} 天')

sell: [20 25 22 30 28]
cost: [15 18 16 22 20]
利润： [5 7 6 8 8]
利润的平均值： 6.8
利润的标准差：1.166
利润最高的天数有 2 天


# Congratulations!⭐